Just trying to force a build
victoriarobotics/victoria_navigation pull request #22
Opened 2017-04-24 04:54 UTC by mwimble

2017-04-24 05:28 UTC, mwimble commented
Includes refactoring, more documentation but more importantly, SeekToGps and MoveToCone work smoothly and travel quickly.

2017-04-25 02:34 UTC, griswaldbrooks requested changes

2017-04-25 02:34 UTC, griswaldbrooks commented on src/move_to_cone.cpp
> +			//cmd_vel.angular.z = ((image_width / 2.0) - last_object_detected_.object_x) > 0 ? yaw_turn_radians_per_sec_ : -yaw_turn_radians_per_sec_;
Remove commented out code.

2017-04-25 02:37 UTC, griswaldbrooks commented
In the past, I've used a lot of sigmoids to scale angular velocity and linear velocity (not to mention range to obstacles).
Usually something line `linear_velocity = k * sigmoid(angular_velocity + m)` where as the angular velocity became large, linear velocity approached zero.

2017-04-25 06:29 UTC, mwimble commented
I like the sigmoid, haven’t used them before. Not seeing how your formula below tends to zero as angular_velocity gets large—doesn’t sigmoid approach +/- 1 as the parameter gets large?

> On Apr 24, 2017, at 4/24 -- 7:37 PM, Griswald Brooks <notifications@github.com> wrote:
> 
> In the past, I've used a lot of sigmoids to scale angular velocity and linear velocity (not to mention range to obstacles).
> Usually something line linear_velocity = k * sigmoid(angular_velocity + m) where as the angular velocity became large, linear velocity approached zero.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296875303>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AKhs3zdrAYmFmRDS9v0J_4k5OwMjBYIwks5rzVx4gaJpZM4NFsh8>.
>

2017-04-25 06:35 UTC, griswaldbrooks commented
So there are multiple "sigmoid" functions, the two I've used the most are:
https://reference.wolfram.com/language/ref/Tanh.html
http://www.wolframalpha.com/input/?source=frontpage-immediate-access&i=x+%2F+sqrt(1%2Bx%5E2)

Depending on how easy it was to shape. If you add 1 and multiple by 0.5,
then you can map it from +/- 1 to [1, 0]

On 24 April 2017 at 23:29, Mike Wimble <notifications@github.com> wrote:

> I like the sigmoid, haven’t used them before. Not seeing how your formula
> below tends to zero as angular_velocity gets large—doesn’t sigmoid approach
> +/- 1 as the parameter gets large?
>
> > On Apr 24, 2017, at 4/24 -- 7:37 PM, Griswald Brooks <
> notifications@github.com> wrote:
> >
> > In the past, I've used a lot of sigmoids to scale angular velocity and
> linear velocity (not to mention range to obstacles).
> > Usually something line linear_velocity = k * sigmoid(angular_velocity +
> m) where as the angular velocity became large, linear velocity approached
> zero.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub <https://github.com/
> victoriarobotics/victoria_navigation/pull/22#issuecomment-296875303>, or
> mute the thread <https://github.com/notifications/unsubscribe-
> auth/AKhs3zdrAYmFmRDS9v0J_4k5OwMjBYIwks5rzVx4gaJpZM4NFsh8>.
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296927474>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAX2f-cx8JybqiM9XrOXKdGMphMLP9c3ks5rzZLegaJpZM4NFsh8>
> .
>

2017-04-25 06:36 UTC, griswaldbrooks commented
Some fun videos
http://griswaldbrooks.com/projects/nao/videos/

On 24 April 2017 at 23:34, Griswald Brooks <griswald.brooks@gmail.com>
wrote:

> So there are multiple "sigmoid" functions, the two I've used the most are:
> https://reference.wolfram.com/language/ref/Tanh.html
> http://www.wolframalpha.com/input/?source=frontpage-
> immediate-access&i=x+%2F+sqrt(1%2Bx%5E2)
>
> Depending on how easy it was to shape. If you add 1 and multiple by 0.5,
> then you can map it from +/- 1 to [1, 0]
>
> On 24 April 2017 at 23:29, Mike Wimble <notifications@github.com> wrote:
>
>> I like the sigmoid, haven’t used them before. Not seeing how your formula
>> below tends to zero as angular_velocity gets large—doesn’t sigmoid approach
>> +/- 1 as the parameter gets large?
>>
>> > On Apr 24, 2017, at 4/24 -- 7:37 PM, Griswald Brooks <
>> notifications@github.com> wrote:
>> >
>> > In the past, I've used a lot of sigmoids to scale angular velocity and
>> linear velocity (not to mention range to obstacles).
>> > Usually something line linear_velocity = k * sigmoid(angular_velocity +
>> m) where as the angular velocity became large, linear velocity approached
>> zero.
>> >
>> > —
>> > You are receiving this because you authored the thread.
>> > Reply to this email directly, view it on GitHub <
>> https://github.com/victoriarobotics/victoria_navigation/
>> pull/22#issuecomment-296875303>, or mute the thread <
>> https://github.com/notifications/unsubscribe-auth/
>> AKhs3zdrAYmFmRDS9v0J_4k5OwMjBYIwks5rzVx4gaJpZM4NFsh8>.
>> >
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296927474>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAX2f-cx8JybqiM9XrOXKdGMphMLP9c3ks5rzZLegaJpZM4NFsh8>
>> .
>>
>
>

2017-04-25 16:39 UTC, mwimble commented
How about some background on these videos.

> On Apr 24, 2017, at 4/24 -- 11:36 PM, Griswald Brooks <notifications@github.com> wrote:
> 
> Some fun videos
> http://griswaldbrooks.com/projects/nao/videos/
> 
> On 24 April 2017 at 23:34, Griswald Brooks <griswald.brooks@gmail.com>
> wrote:
> 
> > So there are multiple "sigmoid" functions, the two I've used the most are:
> > https://reference.wolfram.com/language/ref/Tanh.html
> > http://www.wolframalpha.com/input/?source=frontpage-
> > immediate-access&i=x+%2F+sqrt(1%2Bx%5E2)
> >
> > Depending on how easy it was to shape. If you add 1 and multiple by 0.5,
> > then you can map it from +/- 1 to [1, 0]
> >
> > On 24 April 2017 at 23:29, Mike Wimble <notifications@github.com> wrote:
> >
> >> I like the sigmoid, haven’t used them before. Not seeing how your formula
> >> below tends to zero as angular_velocity gets large—doesn’t sigmoid approach
> >> +/- 1 as the parameter gets large?
> >>
> >> > On Apr 24, 2017, at 4/24 -- 7:37 PM, Griswald Brooks <
> >> notifications@github.com> wrote:
> >> >
> >> > In the past, I've used a lot of sigmoids to scale angular velocity and
> >> linear velocity (not to mention range to obstacles).
> >> > Usually something line linear_velocity = k * sigmoid(angular_velocity +
> >> m) where as the angular velocity became large, linear velocity approached
> >> zero.
> >> >
> >> > —
> >> > You are receiving this because you authored the thread.
> >> > Reply to this email directly, view it on GitHub <
> >> https://github.com/victoriarobotics/victoria_navigation/
> >> pull/22#issuecomment-296875303>, or mute the thread <
> >> https://github.com/notifications/unsubscribe-auth/
> >> AKhs3zdrAYmFmRDS9v0J_4k5OwMjBYIwks5rzVx4gaJpZM4NFsh8>.
> >> >
> >>
> >> —
> >> You are receiving this because your review was requested.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296927474>,
> >> or mute the thread
> >> <https://github.com/notifications/unsubscribe-auth/AAX2f-cx8JybqiM9XrOXKdGMphMLP9c3ks5rzZLegaJpZM4NFsh8>
> >> .
> >>
> >
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296929150>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AKhs35sc6EZVZK3rZIcHxhY1-8ow_lJPks5rzZSIgaJpZM4NFsh8>.
>

2017-04-25 16:54 UTC, griswaldbrooks commented
https://github.com/griswaldbrooks/griswaldbrooks.github.io/raw/master/downloads/griswald_brooks_ms_thesis.pdf
https://github.com/griswaldbrooks/naonav
The core algorithm used there is something called "Potential Fields".
Basically it's the idea that the place you want to go has a virtual attractive force, and obstacles have a virtual repulsive force.

2017-04-25 16:56 UTC, griswaldbrooks commented
Unless you're still making changes, I'm going to merge this/

2017-04-25 17:02 UTC, mwimble commented
Go

Sent from my iPhone

> On Apr 25, 2017, at 9:56 AM, Griswald Brooks <notifications@github.com> wrote:
> 
> Unless you're still making changes, I'm going to merge this/
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-04-25 17:08 UTC, merged

2017-04-25 22:51 UTC, ralphhipps commented
cool videos!!


Ralph

>+<
 |    /\
 |___/  \
 [_@_]   `<
 O O O          IRS!
------------------------------------------------------------------------------------
In the twenty-first century, the robot will take the place
which slave labor occupied in ancient civilization.
 -- Nikola Tesla
------------------------------------------------------------------------------------


On Mon, Apr 24, 2017 at 11:36 PM, Griswald Brooks <notifications@github.com>
wrote:

> Some fun videos
> http://griswaldbrooks.com/projects/nao/videos/
>
> On 24 April 2017 at 23:34, Griswald Brooks <griswald.brooks@gmail.com>
> wrote:
>
> > So there are multiple "sigmoid" functions, the two I've used the most
> are:
> > https://reference.wolfram.com/language/ref/Tanh.html
> > http://www.wolframalpha.com/input/?source=frontpage-
> > immediate-access&i=x+%2F+sqrt(1%2Bx%5E2)
> >
> > Depending on how easy it was to shape. If you add 1 and multiple by 0.5,
> > then you can map it from +/- 1 to [1, 0]
> >
> > On 24 April 2017 at 23:29, Mike Wimble <notifications@github.com> wrote:
> >
> >> I like the sigmoid, haven’t used them before. Not seeing how your
> formula
> >> below tends to zero as angular_velocity gets large—doesn’t sigmoid
> approach
> >> +/- 1 as the parameter gets large?
> >>
> >> > On Apr 24, 2017, at 4/24 -- 7:37 PM, Griswald Brooks <
> >> notifications@github.com> wrote:
> >> >
> >> > In the past, I've used a lot of sigmoids to scale angular velocity and
> >> linear velocity (not to mention range to obstacles).
> >> > Usually something line linear_velocity = k * sigmoid(angular_velocity
> +
> >> m) where as the angular velocity became large, linear velocity
> approached
> >> zero.
> >> >
> >> > —
> >> > You are receiving this because you authored the thread.
> >> > Reply to this email directly, view it on GitHub <
> >> https://github.com/victoriarobotics/victoria_navigation/
> >> pull/22#issuecomment-296875303>, or mute the thread <
>
> >> https://github.com/notifications/unsubscribe-auth/
> >> AKhs3zdrAYmFmRDS9v0J_4k5OwMjBYIwks5rzVx4gaJpZM4NFsh8>.
> >> >
> >>
> >> —
> >> You are receiving this because your review was requested.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/victoriarobotics/victoria_navigation/pull/22#
> issuecomment-296927474>,
> >> or mute the thread
> >> <https://github.com/notifications/unsubscribe-auth/AAX2f-
> cx8JybqiM9XrOXKdGMphMLP9c3ks5rzZLegaJpZM4NFsh8>
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/victoriarobotics/victoria_navigation/pull/22#issuecomment-296929150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALo53Cq84PXHvuAdHRBwgpW070yekofBks5rzZSIgaJpZM4NFsh8>
> .
>